### ISSUE TITLE
Handshake failure

### ISSUE THREAD

**Issue by fredrikaverpil** [danielsmith-eu/python-nikeplus-2013#2]
Hi Daniel, do you also get this handshake failure when attempting to retrieve activity data?

I'm on OS X 10.9.2.

```
iMac:testing fredrik$ python client.py fredrik.averpil@gmail.com 2013-09-01 2013-09-02
Password: 
Traceback (most recent call last):
  File "client.py", line 36, in <module>
    nikeplus.login(args['email'], password)
  File "/Volumes/1TBDrive/Users/fredrik/Projekt/GitHub/nikeplusExporter/testing/nikeplus.py", line 54, in login
    self.opener.open(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

**Comment by fredrikaverpil** [comment]
I'm guessing they changed the way you need to log in. More info: https://developer.nike.com/documentation/api-docs/oauth-services/implicit-grant-flow.html

**Comment by danielsmith-eu** [comment]
💯
